[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
pass = "root"

[kafka]
addrs = ["127.0.0.1:9092"]
topic = "binlog"

[trace_log]
dbs = ["testdb01"]
show_all_field = false
show_query_message = false
highlight = false

[es]
host = "127.0.0.1"
port = 9200
user = ""
pass = ""
data_dir = "/sync"
bulk_size = 4096
source = []
rule = []
flush_bulk_time = 30
skip_no_pk_table = true

